### ISSUE TITLE
Email icon hyperlink doesn't prompt browser email client.

### ISSUE THREAD

**Issue by fleverest** [StraightOuttaCrompton/StraightOuttaCrompton.dev#1]
Cool website :)

Your email button doesn't work, href should be prefixed with `mailto:` rather than `malto:`.

See the following two lines:

https://github.com/StraightOuttaCrompton/StraightOuttaCrompton.dev/blob/main/README.md?plain=1#L25

https://github.com/StraightOuttaCrompton/StraightOuttaCrompton.dev/blob/main/public/index.html#L78

**Comment by StraightOuttaCrompton** [comment]
Thank you for the report. Sorry it took me so long to see this 😅
